stages:
  - build
  - deploy

# first stage  
build_image:
  stage: build
  script:
    - docker build -t ${DOCKER_REPOSITORY/pixalion_client -f docker/Dockerfile .
  only:
    - iac   
  tags:
    - imgbuilder


#second stage
deploy_image:
  stage: deploy
  script:
    - docker login -u ${USERNAME} -p ${PASSWORD} 
    - docker push ${DOCKER_REPOSITORY}/pixalion_client
  only:
    - iac 
  tags:
    - imgbuilder


