apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: talelch/pixalion_client
        imagePullPolicy: Always 
        ports:
        - containerPort: 3000
        env:
          - name: SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: client-config
                key: API_URL
      imagePullSecrets:
      - name: regcred
